### ISSUE TITLE
external tank temperature

### ISSUE THREAD

**Issue by kocour** [bosch-thermostat/bosch-thermostat-client-python#54]
Hi, I'm using this integration (0.28.0) with Bosch CT200 (fw 05.04.00) and I can't see my external tank water temperature in list of entites nor any other similar entity with corresponding data. Assuming the controller has this data, as it should know when to turn on the water heater.
I would appreciate any advice on setting the integration to read and display the current temperature of the external water tank.

**Comment by jerryhh** [comment]
Hi, the current temperature is possible to get by custom sensor. Add this to configuration file
```
# Bosch water tank temp
template:
  - sensor:
      - name: "water_heater.temp"
        unique_id: sensor.dhw1_hotwatertemp
        state: "{{ state_attr('water_heater.dhw1', 'current_temperature') | float(0) }}"
        unit_of_measurement: "°C"
        icon: "mdi:thermometer-water"
```
